kind: CronJob
apiVersion: batch/v1
metadata:
  name: fireflyiii
  labels:
    app: cronjob
    part-of: fireflyiii
spec:
  schedule: "*/60 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: fireflyiii
          containers:
          - name: fireflyiii
            image: curlimages/curl:7.81.0
            command:
            - /bin/sh
            - -c
            - |
              curl "http://fireflyiii.fireflyiii:8080/api/v1/cron/$STATIC_CRON_TOKEN"
            env:
            - name: STATIC_CRON_TOKEN
              valueFrom:
                secretKeyRef:
                  name: fireflyiii
                  key: STATIC_CRON_TOKEN
            volumeMounts:
            - name: fireflyiii-secrets
              mountPath: "/mnt/vault"
              readOnly: true
          volumes:
          - name: fireflyiii-secrets
            csi:
              driver: "secrets-store.csi.k8s.io"
              readOnly: true
              volumeAttributes:
                secretProviderClass: "fireflyiii"
